{
 "title": "FishDockSQL",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "PPT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT \"time\", pbo_ppt_watt FROM metrics ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT \"time\", temp_c FROM metrics ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Current Players Lichess.org",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT lichess_online, \"time\", lichess_games FROM metrics ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  { "title": "Fishnet Docker Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Mnps pro Client (Speed from fishnet-log)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT\r\n  \"time\",\r\n  container_name AS \"metric\",\r\n  (nps_si * cores) / 1000000.0 AS \"value\"\r\nFROM \r\n  metrics\r\nWHERE \r\n  container_name != 'fishnet-0'\r\n  AND \"time\" > $__timeFrom() -- Nutzt den Zeitfilter von Grafana\r\nORDER BY \r\n  1, 2;"
    }
   ]
  },
  {
   "title": "Mnps average last 2 Batches",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "si:MNps" } },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT\r\n  container_name AS \"metric\",\r\n  AVG(nps_si * cores) / 1000000 AS \"value\"\r\nFROM (\r\n  SELECT\r\n    container_name,\r\n    nps_si,\r\n    cores,\r\n    ROW_NUMBER() OVER (PARTITION BY container_name ORDER BY \"time\" DESC) as rn\r\n  FROM \r\n    metrics\r\n  WHERE \r\n    container_name != 'fishnet-0'\r\n    AND \"time\" > NOW() - INTERVAL '10 minutes'\r\n) AS subquery\r\nWHERE \r\n  rn <= 2 -- Durchschnitt der letzten 2 Zeilen\r\nGROUP BY \r\n  container_name\r\nORDER BY \r\n  container_name ASC;"
    }
   ]
  },
  {
   "title": "Real MNps (incl. Network, Lila Server)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "si:Nps" } },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT\r\n  SUM(nps_per_worker) AS \"Gesamt-Speed\"\r\nFROM (\r\n  SELECT\r\n    container_name,\r\n    (MAX(total_nodes) - MIN(total_nodes)) / \r\n    NULLIF(EXTRACT(EPOCH FROM (MAX(\"time\") - MIN(\"time\"))), 0) AS nps_per_worker\r\n  FROM \r\n    worker_stats\r\n  WHERE \r\n    \"time\" > NOW() - INTERVAL '5 minutes'\r\n  GROUP BY \r\n    container_name\r\n) AS subquery"
    }
   ]
  },
  {
   "title": "Real MNps (incl. Network, Lila Server)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "suffix: MNps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT\r\n  all_workers.container_name AS \"metric\",\r\n  COALESCE(recent_speed.nps, 0) / 1000000 AS \"value\" -- Hier erzwingen wir Mega\r\nFROM (\r\n  SELECT DISTINCT container_name \r\n  FROM worker_stats \r\n  WHERE container_name != 'fishnet-0'\r\n) AS all_workers\r\nLEFT JOIN (\r\n  SELECT\r\n    container_name,\r\n    (MAX(total_nodes) - MIN(total_nodes)) / \r\n    NULLIF(EXTRACT(EPOCH FROM (MAX(\"time\") - MIN(\"time\"))), 0) AS nps\r\n  FROM \r\n    worker_stats\r\n  WHERE \r\n    \"time\" > NOW() - INTERVAL '5 minutes'\r\n    AND container_name != 'fishnet-0'\r\n  GROUP BY \r\n    container_name\r\n) AS recent_speed ON all_workers.container_name = recent_speed.container_name\r\nORDER BY \r\n  all_workers.container_name ASC;"
    }
   ]
  },
  {
   "title": "MNodes pro Batch (für Instanz)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "si: MN/Batch" } },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT\r\n  time_clean AS \"time\",\r\n  metric AS \"metric\",\r\n  value\r\nFROM (\r\n  SELECT\r\n    ws.time_clean,\r\n    ws.container_name AS metric,\r\n    SUM(ws.diff) / NULLIF(SUM(m.batch_count), 0) AS value\r\n  FROM (\r\n    SELECT\r\n      $__timeGroup(\"time\"::timestamp, $__interval) AS time_clean,\r\n      container_name,\r\n      (MAX(total_nodes) - MIN(total_nodes)) AS diff\r\n    FROM worker_stats\r\n    WHERE $__timeFilter(\"time\"::timestamp)\r\n    GROUP BY 1, 2\r\n  ) AS ws\r\n  INNER JOIN (\r\n    SELECT\r\n      $__timeGroup(\"time\"::timestamp, $__interval) AS time_clean,\r\n      container_name,\r\n      COUNT(DISTINCT batch_id) AS batch_count\r\n    FROM metrics\r\n    WHERE $__timeFilter(\"time\"::timestamp)\r\n    GROUP BY 1, 2\r\n  ) AS m ON ws.time_clean = m.time_clean AND ws.container_name = m.container_name\r\n  GROUP BY 1, 2\r\n) AS final_result\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "G Nodes per h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "si:Nodes" } },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT\r\n  time_clean AS \"time\",\r\n  SUM(diff) AS \"value\"\r\nFROM (\r\n  SELECT\r\n    $__timeGroup(\"time\"::timestamp, $__interval) AS time_clean,\r\n    container_name,\r\n    MAX(total_nodes) - MIN(total_nodes) AS diff\r\n  FROM \r\n    worker_stats\r\n  WHERE \r\n    $__timeFilter(\"time\"::timestamp)\r\n  GROUP BY \r\n    1, 2\r\n) AS subquery\r\nGROUP BY \r\n  1\r\nORDER BY \r\n  1"
    }
   ]
  },
  {
   "title": "Batch / h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"time\", $__interval),\r\n  COUNT(batch_id) AS \"value\"\r\nFROM\r\n  metrics\r\nWHERE\r\n  $__timeFilter(\"time\")\r\nGROUP BY\r\n  1\r\nORDER BY\r\n  1"
    }
   ]
  },
  {
   "title": "G Nodes per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "si:Nodes" } },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT\r\n  time_clean AS \"time\",\r\n  SUM(diff) AS \"value\"\r\nFROM (\r\n  SELECT\r\n    $__timeGroup(\"time\"::timestamp, $__interval) AS time_clean,\r\n    container_name,\r\n    MAX(total_nodes) - MIN(total_nodes) AS diff\r\n  FROM \r\n    worker_stats\r\n  WHERE \r\n    $__timeFilter(\"time\"::timestamp)\r\n  GROUP BY \r\n    1, 2\r\n) AS subquery\r\nGROUP BY \r\n  1\r\nORDER BY \r\n  1"
    }
   ]
  },
  {
   "title": "Real MNps (Network, Lila Server)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "si:Nps" } },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT\r\n  time_bucket AS \"time\",\r\n  SUM(nps_per_worker) AS \"Gesamt-Speed_SI\"\r\nFROM (\r\n  SELECT\r\n    container_name,\r\n    $__timeGroup(\"time\", 1h) AS time_bucket,\r\n    (MAX(total_nodes) - MIN(total_nodes)) / \r\n    NULLIF(EXTRACT(EPOCH FROM (MAX(\"time\") - MIN(\"time\"))), 0) AS nps_per_worker\r\n  FROM \r\n    worker_stats\r\n  WHERE \r\n    $__timeFilter(\"time\")\r\n  GROUP BY \r\n    container_name, time_bucket\r\n) AS subquery\r\nWHERE nps_per_worker > 0\r\nGROUP BY \r\n  1\r\nORDER BY \r\n  1;"
    }
   ]
  },
  {
   "title": "Varianten Schach",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT variant, COUNT(variant) FROM metrics WHERE $__timeFilter(\"time\") GROUP BY variant ORDER BY variant LIMIT 50 "
    }
   ]
  },
  {
   "title": "Batch per Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"time\", $__interval),\r\n  COUNT(batch_id) AS \"value\"\r\nFROM\r\n  metrics\r\nWHERE\r\n  $__timeFilter(\"time\")\r\nGROUP BY\r\n  1\r\nORDER BY\r\n  1"
    }
   ]
  },
  {
   "title": "Last errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT status, error_msg, \"time\" FROM metrics WHERE status <> 'OK' ORDER BY \"time\" DESC "
    }
   ]
  },
  {
   "title": "Fehlerquote",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT status, COUNT(status) FROM metrics WHERE $__timeFilter(\"time\") GROUP BY status LIMIT 50 "
    }
   ]
  },
  {
   "title": "Analyse Typ",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT analysis_type, COUNT(analysis_type) FROM metrics WHERE $__timeFilter(\"time\") GROUP BY analysis_type ORDER BY analysis_type LIMIT 50 "
    }
   ]
  },
  {
   "title": "Nodes per s",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "suffix: Mnps" } },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT\r\n  all_workers.container_name AS \"metric\",\r\n  COALESCE(recent_speed.nps, 0) / 1000000 AS \"value\" -- Hier erzwingen wir Mega\r\nFROM (\r\n  SELECT DISTINCT container_name \r\n  FROM worker_stats \r\n  WHERE container_name != 'fishnet-0'\r\n) AS all_workers\r\nLEFT JOIN (\r\n  SELECT\r\n    container_name,\r\n    (MAX(total_nodes) - MIN(total_nodes)) / \r\n    NULLIF(EXTRACT(EPOCH FROM (MAX(\"time\") - MIN(\"time\"))), 0) AS nps\r\n  FROM \r\n    worker_stats\r\n  WHERE \r\n    \"time\" > NOW() - INTERVAL '5 minutes'\r\n    AND container_name != 'fishnet-0'\r\n  GROUP BY \r\n    container_name\r\n) AS recent_speed ON all_workers.container_name = recent_speed.container_name\r\nORDER BY \r\n  all_workers.container_name ASC;"
    }
   ]
  },
  {
   "title": "Mnps pro Client",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "si:nps" } },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT\r\n  container_name AS \"metric\",\r\n  COALESCE(\r\n    (MAX(total_nodes) - MIN(total_nodes)) / \r\n    NULLIF(EXTRACT(EPOCH FROM (MAX(\"time\") - MIN(\"time\"))), 0), \r\n    0\r\n  ) AS \"value\"\r\nFROM \r\n  worker_stats\r\nWHERE \r\n  \"time\" > NOW() - INTERVAL '10 minutes' -- Zeitraum etwas größer wählen für Stabilität\r\nGROUP BY \r\n  container_name\r\nORDER BY \r\n  \"container_name\" ASC; -- Die \"Sorgenkinder\" mit 0 stehen dann ganz oben"
    }
   ]
  },
  { "title": "Lichess Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Players Lichess.org Chess.com",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT \"time\", lichess_online, chess_com_players FROM metrics WHERE $__timeFilter(\"time\") "
    }
   ]
  },
  {
   "title": "USER/SYSTEM Acquired Queued Oldest",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT \"time\", user_acquired, user_queued, user_oldest, system_acquired, system_queued, system_oldest FROM metrics WHERE $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "Callback Time Lichess.org Chess.com (not Cloudflare or OVH ping)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT \"time\", lichess_ping, chess_com_ping FROM metrics WHERE $__timeFilter(\"time\") "
    }
   ]
  },
  {
   "title": "PPT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT \"time\", pbo_ppt_watt FROM metrics WHERE $__timeFilter(\"time\") "
    }
   ]
  },
  {
   "title": "CPU Temperature ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "fishnet_stats",
     "rawSql": "SELECT \"time\", temp_c FROM metrics WHERE $__timeFilter(\"time\") "
    }
   ]
  }
 ]
}